version: '3.7'
services:
  go-poc-postgresql:
    image: postgres
    container_name: go-poc-postgresql
    environment:
      - POSTGRES_DB=rainbow_database
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD=4y7sV96vA9wv46VR
    ports:
      - '5432:5432'
    volumes:
      - poc_pg_data:/var/lib/postgresql
  go-poc-redis:
    image: docker.io/bitnami/redis:7.0
    container_name: go-poc-redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
  go-poc-prometheus:
    image: prom/prometheus:v2.40.5
    container_name: go-poc-prometheus
    ports:
      - '9000:9090'
    volumes:
      - prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  go-poc-grafana:
    image: grafana/grafana:latest
    container_name: go-poc-grafana
    depends_on:
      - go-poc-prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - '3000:3000'
volumes:
  poc_pg_data:
  prometheus-data:
  grafana_data:
