version: '3.7'
services:
  go-poc-postgresql:
    image: postgres:16.1
    container_name: go-poc-postgresql
    environment:
      - POSTGRES_DB=rainbow_database
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD=4y7sV96vA9wv46VR
    ports:
      - '5433:5432'
    volumes:
      - poc_pg_data:/var/lib/postgresql
  go-poc-redis:
    image: docker.io/bitnami/redis:7.0
    container_name: go-poc-redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
volumes:
  poc_pg_data:
  