version: '3.7'
services:
  go-poc-postgresql:
    image: postgres
    environment:
      - POSTGRES_DB=rainbow_database
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD=4y7sV96vA9wv46VR
    ports:
      - '5432:5432'
    volumes:
      - poc_pg_data:/var/lib/postgresql
  go-poc-redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
  go-poc-prometheus:
    image: prom/prometheus:v2.40.5
    ports:
      - '9000:9090'
    volumes:
      - prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
volumes:
  poc_pg_data:
  prometheus-data: