http:
  server:
    port: 8443
app:
  tenant: 1
  pgUrl: postgres://posgres:4y7sV96vA9wv46VR@localhost:5432/rainbow_database
  pgPoolMin: 5
  pgPoolMax: 5
  accessLogFile: ./access.log
  stdLogFile: ./micro-fiber-test.log
  oauthClientId: fe776acfe3df20bae9eb
  oauthClientSecret: 18733805950f7b29477ed4dde4e188f6df18e4b0
  oauthGitlab: https://github.com/login/oauth/authorize
  oauthCallback: https://github.com/login/oauth/access_token?client_id=%s&client_secret=%s&code=%s&code_verifier=%s
  oauthRedirectUri: https://localhost:8443/oauth/redirect
  oauthDebug: true
  redisHost: localhost
  redisPort: 6379
  redisUser:
  redisPass: