title="SQL Queries"
[organizations]
create="insert into organizations(tenant_id,code,label,type,status) values($1,$2,$3,$4,$5) returning id"
update="update organizations set label=$1 where code=$2"
delete="delete from organizations where code=$1"
findbycode="select id,tenant_id,code,label,type,status from organizations where code=$1"
findall="select id,tenant_id,code,label,type,status from organizations where tenant_id=$1"
existsbycode="select count(1) from organizations where tenant_id=$1 and code=$2"
findbylabel="select id from organizations where tenant_id=$1 and label=$2"
[users]
create="insert into users(tenant_id,org_id,external_id,last_name,first_name,middle_name,login,email,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning id"
update_by_external_id="update users set last_name=$1,first_name=$2,middle_name=$3,login=$4,email=$5 where external_id=$6"
delete_by_external_id="delete from users where external_id=$1"
email_in_user="select id,external_id from users where email=$1"
find_by_login="select id,external_id from users where login=$1"
find_by_external_id="select id,external_id,last_name,first_name,middle_name,login,email,status from users where tenant_id=$1 and org_id=$2 and external_id=$3"
find_by_query="select id,external_id,last_name,first_name,middle_name,login,email,status from users"
[sectors]
create="insert into sectors(tenant_id,org_id,code,label,parent_id,has_parent,depth,status) values($1,$2,$3,$4,$5,$6,$7,$8) returning id"
deletebyorgid="delete from sectors where org_id=$1"
findbytenantorg="select id,tenant_id,org_id,code,label,parent_id,has_parent,depth,status from sectors where tenant_id=$1 and org_id=$2 order by label asc"
findbylabel="select id,code from sectors where tenant_id=$1 and label=$2"
findbycode="select id,tenant_id,org_id,code,label,parent_id,has_parent,depth,status from sectors where tenant_id=$1 and code=$2"
findroot="select id from sectors where tenant_id=$1 and org_id=$2 and has_parent=$3"
delete="delete from sectors where tenant_id=$1 and (id=$2 or parent_id=$3)"
update="update sectors set label=$1 where id=$2 and tenant_id=$3"