global:
  scrape_interval: 5s
  scrape_timeout: 3s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: golang
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: user
      password: pass
    static_configs:
      - targets:
          - '192.168.1.15:8443'